GOOGLE_APP_ID: "630681348185-jd8n4po59i99v7tsp4a1mr6fag2qv4m1.apps.googleusercontent.com"
GOOGLE_APP_SECRECT: "Ls_4WHqPbk1ndxb4-sWHb4vm"
GOOGLE_RECAPT_SITE_KEY: '6Le6yqYUAAAAAHw-Rwb1x1LxE14SmqzOV3gCDoEM'
GOOGLE_RECAPT_SECRET_KEY: '6Le6yqYUAAAAAINvtR8gR4xiLG5G6svn3pMEDWRk'
FACEBOOK_APP_ID: '2948025641904657'
FACEBOOK_APP_SECRET: 'df28ae73323ce8ea3a4c5636df1ad2dc'
